#Exception Messages
user.not.found=Requested user with email {0} does not exist.
user.duplicate=User with email {0} already exists.
user.exception=Error while processing user request.
category.not.found=Requested category with id {0} does not exist.
category.duplicate=Category with name {0} already exists.
category.used.elsewhere=Category with id {0} is used by other scopes.
category.exception=Error while processing category request.
scope.not.found=Requested scope with id {0} does not exist.
scope.duplicate=Scope with name {0} already exists.
scope.used.elsewhere=Scope with id {0} is used by other costumes.
scope.exception=Error while processing scope request.
costume.not.found=Requested costume with id {0} does not exist.
costume.duplicate=Costume with name {0} already exists.
costume.exception=Error while processing costume request.